### ISSUE TITLE
Can't get result 

### ISSUE THREAD

**Issue by vmeng** [waseem/long-audio-aligner#2]
I create a file named 1.txt and run:

$ java -ms400m -mx1500m -jar bin/aligner.jar ./resource/wav/oov_numbers.wav ./1.txt
Transcription: 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -3
    at java.util.ArrayList.get(ArrayList.java:324)
    at edu.cmu.sphinx.linguist.language.grammar.AlignerGrammar.addForwardJumps(AlignerGrammar.java:202)
    at edu.cmu.sphinx.linguist.language.grammar.AlignerGrammar.createGrammar(AlignerGrammar.java:147)
    at edu.cmu.sphinx.linguist.language.grammar.Grammar.allocate(Grammar.java:116)
    at edu.cmu.sphinx.linguist.aflat.AFlatLinguist.allocate(AFlatLinguist.java:260)
    at edu.cmu.sphinx.decoder.search.AlignerSearchManager.allocate(AlignerSearchManager.java:752)
    at edu.cmu.sphinx.decoder.AbstractDecoder.allocate(AbstractDecoder.java:87)
    at edu.cmu.sphinx.recognizer.Recognizer.allocate(Recognizer.java:168)
    at edu.cmu.sphinx.demo.aligner.Aligner.allocate(Aligner.java:240)
    at edu.cmu.sphinx.demo.aligner.Aligner.align(Aligner.java:162)
    at edu.cmu.sphinx.demo.aligner.AlignerDemo.main(AlignerDemo.java:45)

I think this is config.xml error. Is any body can fix it?

**Comment by waseem** [comment]
@vmeng Can you post your txt and audio file somewhere?

**Comment by vmeng** [comment]
The audio file is /resource/wav/oov_numbers.wav in git, and the 1.txt file is an empty file.

**Comment by waseem** [comment]
1.txt should not be an empty file.

On Thu, Jul 18, 2013 at 12:27 PM, vmeng notifications@github.com wrote:

> The audio file is /resource/wav/oov_numbers.wav in git, and the 1.txt file
> is an empty file.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/waseem/long-audio-aligner/issues/2#issuecomment-21165940
> .

## 

Waseem
Blog: http://waseem-ahmad.com
Twitter: http://twitter.com/_waseem

**Comment by vmeng** [comment]
got it.

It should be use commend:
$java -ms400m -mx1500m -jar bin/aligner.jar ./resource/wav/oov_numbers.wav ./resource/transcription/oov_numbers.txt

Thanks
